### PR TITLE
WIP: Improving walkthroughs and victory conditions

### PR DESCRIPTION
**Pull request by MarcCote**
This PR is a work in progress.

This PR aims at improving the existing walkthroughs and adding new ones.
This PR also makes sure the victory condition for the games works as expected.

# Progress
- [x] 905.z5
- [x] acorncourt.z5
- [x] advent.z5
- [x] adventureland.
- [x] afflicted.z8
- [x] anchor.z8 **(Incomplete: 99/100)**
- [x] awaken.z5
- [x] balances.z5 **(Incomplete: 50/51)**
- [x] ballyhoo.z3
- [x] curses.z5 **(Incomplete: 450/550)**
- [x] cutthroat.z3
- [x] deephome.z5
- [x] detective.z5
- [x] dragon.z5
- [x] enchanter.z3
- [x] enter.z5
- [x] gold.z5
- [x] hhgg.z3
- [x] hollywood.z3
- [x] huntdark.z5
- [x] infidel.z3
- [x] inhumane.z5
- [x] jewel.z5
- [x] karn.z5
- [x] lgop.z3 **(Unsupported game)**
- [x] library.z5
- [x] loose.z5
- [x] lostpig.z8
- [x] ludicorp.z5
- [x] lurking.z3
- [x] moonlit.z5
- [x] murdac.z5
- [x] night.z5
- [ ] omniquest.z5
- [x] partyfoul.z8
- [x] pentari.z5  **(Incomplete: 60/70)**
- [x] planetfall.z3
- [x] plundered.z3
- [x] reverb.z5
- [x] seastalker.z3
- [x] sherlock.z5
- [x] snacktime.z8
- [x] sorcerer.z3
- [x] spellbrkr.z3
- [x] spirit.z5
- [x] temple.z5
- [x] theatre.z5  **(Incomplete: 47/50)**
- [x] trinity.z4
- [x] tryst205.z5
- [x] weapon.z5
- [x] wishbringer.z3
- [x] yomomma.z8  **(Incomplete: 34/35)**
- [x] zenon.z5
- [x] zork1.z5
- [x] zork2.z5
- [x] zork3.z5
- [x] ztuu.z5

# Contributing
To contribute, make a PR to [MarcCote/jericho/tree/walkthroughs](https://github.com/MarcCote/jericho/compare/walkthroughs...MarcCote:walkthroughs). See the documentation to know which [games are supported by Jericho](https://jericho-py.readthedocs.io/en/latest/tutorial_quick.html#acquire-games).

In this PR, there are two handy scripts: `tools/find_walkthrough.py` and `tools/test_games.py`.

## find_walkthrough.py
Usage: `python find_walkthrough.py gamefile.z5 --walkthrough walkthrough.txt`

This script plays `gamefile.z5` by applying the commands found in `walkthrough.txt` (one command per line). After each command, the resulting `obs` string is displayed and a prompt is presented to the user to provide the next command. If available, the proposed command form the walkthrough is shown between`[]` and will be used as default if the user types an empty command.

For convenience, one can easily skip to the n-th command of the walkthrough by using the `--skip-to` argument (e.g. `python find_walkthrough.py gamefile.z5 --walkthrough walkthrough.txt --skip-to N`).

### Special commands
- `undo`: Users can use `undo` which will revert the previous action.
- `debug`: Drop into `ipdb` mode (requires `pip install ipdb`).
- `break`: Stop the script, printing the list of commands compatible with `jericho/game_info.py`.

## test_games.py
Usage: `python test_games filename [filename ...]`

This script goes over all provided game files and for each, it checks if the corresponding walkthrough in `jericho/game_info.py` is complete and valid.

Example:
`python tools/test_games.py roms/*`
image

### CODE REVIEW

**Comment by MarcCote** [comment]
I just noticed the game `sorcerer` requires the manual mid-play (after ~50 moves) to know which buttons to press.

**Comment by mhauskn** [comment]
Marc - this is awesome! You're right that the game-over detection is broken for many of the games. 

Which games are giving issues with score detection? Zork2?

**Comment by MarcCote** [comment]
@mhauskn in the screenshot above (I'll update it every time I add new walkthrough), all games with a "Done but score X/Y". At the moment, that would be: anchor, balances, enchanter, infidel, sorcerer, and zork2.

**Comment by mhauskn** [comment]
So for a game like anchor - we are actually getting all 100 possible points, but get_score() is returning 99?

**Comment by MarcCote** [comment]
yes, that's what I see.

**Comment by mhauskn** [comment]
I'd like to help gathering/generating walkthroughs. Are there games that I can start working on that you're not focusing on?

**Comment by MarcCote** [comment]
I finished the list of walkthroughs I had (mostly Infocom games). I was planning on starting at the top of the list. You can start at the bottom, or vice versa.

**Comment by mhauskn** [comment]
Great, I'll start with ztuu and work my way up.

**Comment by mhauskn** [comment]
I made it through ztuu/zenon/yomomma today. Back for more on Tuesday.

**Comment by MarcCote** [comment]
Just added a few more walkthroughs.

**Comment by mhauskn** [comment]
Finished walkthroughs for weapon/tryst205/trinity today.

**Comment by mhauskn** [comment]
Finished walkthroughs for theater and temple today. Still working on spirit.

**Comment by MarcCote** [comment]
@mhauskn I added a check list in my first post to keep track of what's completed. I think you have write permission to check items.

**Comment by mhauskn** [comment]
I've finished adding most of the games and have fixed the score detection in many games. How to proceed - can I send a PR from my local to your branch?

**Comment by MarcCote** [comment]
@mhauskn yes that would be the easiest thing to do. You manage to find a walkthrough for inhumane!

**Comment by mhauskn** [comment]
I found this youtube video <https://www.youtube.com/watch?v=hhWIbwBRqLM>.

**Comment by mhauskn** [comment]
I created a branch jericho/walkthroughs branch which has my changes. When
trying initiate a PR against your branch, it only seems to want to merge
your branch into mine (weird). Not sure what soln is.

**Comment by MarcCote** [comment]
@mhauskn I have merge your commit to this PR. I have updated the figure in my first post. Note how the score is broken for some of the game.

**Comment by mhauskn** [comment]
I've fixed the remaining score detection issues and finished the walkthrough for Spellbreaker. All of the remaining tests that are failing are due to the walkthroughs themselves reaching victory but not collecting all possible points. In my opinion, this is okay and it may be quite difficult to figure out how to get all the possible points in each game. The only open issue that remains is finding/creating a walkthrough for Omniquest.

I've pushed my edits into a branch called pull26 - can you merge them into your PR?

**Comment by MarcCote** [comment]
@mhauskn merged into this PR. I've updated the figure and the check list. If that looks good to you, feel free to merge the PR into Jericho.

Also, I have annotated some of the walkthroughs, do you want them?

Good job! :D

**Comment by mhauskn** [comment]
What do you mean by annotated walkthroughs?

**Comment by mhauskn** [comment]
Marc - can you remove the annotated walkthroughs (in the walkthroughs directory) and bump the version number?

**Comment by MarcCote** [comment]
Here you go @mhauskn

**Pull request merged**
